---
resoureces:
- name: source-code
  type: git
  source:
    uri: 
    branch: master

jobs: 
- name: compile-app
  plan:
  - get: source-code
  - task: first-task
    config: 
      platform: linux
      image_resource: 
        type: docker-iamge
        source: 
          repository: mcr.microsoft.com/dotnet/core/sdk
          tag: 2.2
      inputs: 
      - name: source-code
      run: 
        path: sh
        args: 
        - -exec
        - |
          dotnet build ./source-code/
- name: run-app